name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - uses: actions/setup-node@main
        with:
          node-version: 16
          check-latest: true

      - name: Node.js version
        run: node --version

      - name: npm version
        run: npm --version

      - name: Install dependencies
        run: npm ci

      - name: Commitlint
        run: npm run commitlint:all

      - name: Prettier
        run: npm run prettier

      - name: ESLint
        run: npm run lint

      - name: Tests
        run: npm run test:ci

      - name: Publish (test)
        run: npm run publish:test

      - name: Docs
        run: npm run docs:build

      - name: Coverage
        run: npm run coverage:ci

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
